### ISSUE TITLE
`Timeout Error: [Errno 110] Connection timed out` occurs when calling set_brightness function

### ISSUE THREAD

**Issue by Joseph0M** [Joseph0M/DIYson-SolarCycle#2]
Error:
 ```
Traceback (most recent call last):
  File "/home/diyson/.local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/diyson/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/diyson/.local/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/diyson/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/diyson/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/diyson/.local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/diyson/.local/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/diyson/.local/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/diyson/PiZero/API/src/endpoints/v1/lamp.py", line 66, in set_lamp_brightness
    HW().set_brightness(start=0, end=bri,direction=direction,increment=incriment)
  File "/home/diyson/PiZero/DIYson_lib/Hardware.py", line 93, in set_brightness
    payload = self.pi2pi.get_payload('s',[start,end,direction,increment])
  File "/home/diyson/PiZero/DIYson_lib/i2c.py", line 53, in get_payload
    response = deserialize(self.read())
  File "/home/diyson/PiZero/DIYson_lib/i2c.py", line 45, in read
    bit=self.bus.read_byte(self.addr)
  File "/home/diyson/.local/lib/python3.9/site-packages/smbus2/smbus2.py", line 396, in read_byte
    ioctl(self.fd, I2C_SMBUS, msg)
TimeoutError: [Errno 110] Connection timed out
```
Cause: set_brightness Loop runs during read sequence, causing the While Loop to hang.
Repeatability: 100% (Call `set_brightness` function, AutoMode or appropriate API call)
Device: Slave (Pico W)

**Comment by Joseph0M** [comment]
Marked Completed. Waiting on the next release
